export enum EExpenseStatus {
  WAITING_COMMITMENT = 'WAITING_COMMITMENT',
  PARTIALLY_COMMITTED = 'PARTIALLY_COMMITTED',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
}